### ISSUE TITLE
Mouse clicks are selecting the previously highlighted option

### ISSUE THREAD

**Issue by felixsan** [mitosch/textual-select#2]
I started seeing a weird behavior when I switched to `textual` 0.13.0 and `textual-select` 3.0.  When opening the select with a mouse and clicking on an option, the option selected is the one that was previously highlighted, not the one I'm clicking.  On subsequent clicks, the one I had clicked previously is now highlighted, and clicking any option will select it.  I've only noticed this behavior when using the mouse, as I can still select the correct option via the keyboard.  Here's a screengrab of what I see when using the example:
![repro](https://user-images.githubusercontent.com/552438/224529216-358afec7-b753-4135-ac1f-e0037df1d55c.gif)

**Comment by mitosch** [comment]
Thank you very much for reporting this issue, which I did not detect so far. I will look into it as soon as possible and provide an update.

**Comment by mitosch** [comment]
The bug has been fixed with version 0.3.1

Thanks again for reporting and using this plugin.
